[package]
name = "sp1-primitives"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
p3-field = { workspace = true }
p3-baby-bear = { workspace = true }
p3-poseidon2 = { workspace = true }
p3-symmetric = { workspace = true }
itertools = "0.13.0"
