[package]
name = "helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ecies = {version = "0.2.6", features = ["std"]}
openssl = { version = "0.10.57", features = ["vendored"] }
ethers = { version = "2", features = ["rustls"] }
aes-gcm = "0.10.3"
hex = "0.4.3"
serde = "1.0.178"

[lib]
name = "helper"
path = "lib.rs"
