[package]
version = "0.1.0"
name = "kalypso-program"
edition = "2021"

[dependencies]
rsa = "0.6"
sp1-sdk = { path = "../../../sdk" }
hex = "0.4"

[build-dependencies]
sp1-helper = { path = "../../../helper" }
