[package]
name = "sp1-recursion-gnark-ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
p3-field = { workspace = true }
p3-symmetric = { workspace = true }
p3-baby-bear = { workspace = true }
sp1-recursion-compiler = { path = "../compiler" }
sp1-core = { path = "../../core" }
serde = "1.0.201"
serde_json = "1.0.117"
tempfile = "3.10.1"
rand = "0.8"
log = "0.4.21"
num-bigint = "0.4.5"
cfg-if = "1.0"
bincode = "1.3.3"
anyhow = "1.0.86"
sha2 = "0.10.8"
hex = "0.4.3"

[build-dependencies]
bindgen = "0.69.4"
cc = "1.0"
cfg-if = "1.0"

[features]
native = []
